name: Notificar cambios en main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: Push Detectado" \
               -H "Priority: high" \
               -d "El usuario de GitHub ${{ github.actor }} ha realizado cambios al repositorio: https://github.com/justindff/practica-ic" \
               https://ntfy.sh/devops-itla

